services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
      - "${DEBUG_SERVER_PORT}:${DEBUG_SERVER_PORT}"
    command: [ "sh", "-c", "sleep 10 && ./main" ]

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.116.1
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - app